#!/usr/bin/env bash
# Commits the content regenerated by nuxt/scripts/sync-content.mjs to a
# fresh branch and opens a merge request for review. The sync job never
# pushes straight to main — content changes go through the same MR review
# as everything else.
set -euo pipefail

cd "$(dirname "$0")/../.."

if git diff --quiet -- nuxt/content/articles-data nuxt/public/images/writing 2>/dev/null \
  && [ -z "$(git status --porcelain -- nuxt/content/articles-data nuxt/public/images/writing)" ]; then
  echo "No content changes from Drupal — nothing to sync."
  exit 0
fi

branch="content-sync/drupal-$(date +%Y%m%d-%H%M%S)"
git config user.name "gitlab-ci"
git config user.email "ci@stuar.tc"
git checkout -b "$branch"
git add nuxt/content/articles-data nuxt/public/images/writing
git commit -m "chore(content): sync articles from Drupal"

remote_url="https://oauth2:${GITLAB_API_TOKEN}@gitlab.local/stuart-clark/stuar.tc.git"
git push "$remote_url" "$branch"

curl_retry=(curl -s --retry 3 --retry-delay 2 --max-time 30 --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN")
mr_url="${CI_API_V4_URL:-http://gitlab.local/api/v4}/projects/${CI_PROJECT_ID:-2}/merge_requests"

"${curl_retry[@]}" --request POST "$mr_url" \
  --form "source_branch=$branch" \
  --form "target_branch=main" \
  --form "title=chore(content): sync articles from Drupal" \
  --form "description=Automated content sync from the Drupal backend (Tome + JSON:API) via the manual \`sync:drupal-content\` CI job. Review the diff in nuxt/content/articles-data/ before merging."
