#!/bin/bash

## Description: Install the Drupal using Tome
## Usage: install
## Example: "ddev install"

composer install
drush tome:install -y
drush php-eval 'node_access_rebuild();'
drush cache:rebuild
