#!/bin/bash

## Description: Run PHPStan static analysis
## Usage: phpstan [options]
## Example: "ddev phpstan" or "ddev phpstan analyse web/modules/custom"

ARGS="$@"

if [ -n "$ARGS" ]; then
  php -d memory_limit=-1 vendor/bin/phpstan "$ARGS"
else
  php -d memory_limit=-1 vendor/bin/phpstan analyse
fi
