#!/bin/bash

## Description: Run PHPUnit tests
## Usage: phpunit [test-path]
## Example: "ddev phpunit" or "ddev phpunit web/modules/custom/stuartc_tests/tests/src/Kernel"

if [ "$#" -gt 0 ]; then
  php -d memory_limit=-1 vendor/bin/phpunit -c /var/www/html/phpunit.xml "$@"
else
  php -d memory_limit=-1 vendor/bin/phpunit -c /var/www/html/phpunit.xml
fi
